### ISSUE TITLE
Problems installing bundle

### ISSUE THREAD

**Issue by Eragon666** [sonatra/SonatraSecurityBundle#6]
Hi, I am trying to setup our application with Symfony3.1 with the SonatraSecurityBundle. But after trying to do php app/console config:dump-reference SonatraSecurityBundle I get the following error:

The service "sonatra_security.expression.has_org_role.evaluator" has a dependency on a non-existent service "sonatra_security.organizational_context".

**Comment by francoispluchino** [comment]
You must enable the `organizational_context` option or disable the jms expression `has_org_role`:

```yaml
sonatra_security:
    expression:
        has_org_role: false
```
